### ISSUE TITLE
Heading Links

### ISSUE THREAD

**Issue by abbeyperini** [abbeyperini/Portfolio2.0#11]
Because react-markdown does not parse heading anchors, I'm getting "target source does not exist" errors for my table of contents links and they do not work. I tried a handful of solutions, and there are more listed in [the issues](https://github.com/remarkjs/react-markdown/issues/69), including remark and rehype plugins that are deprecated or involve installing multiple plugins like https://github.com/remarkjs/remark-toc

**Comment by AlexMNet** [comment]
I just stumbled across your post while trying to figure out a solution for the same thing. And yes react-markdown does not attach ids to heading tags so you can't link to them without plugins or writing helper functions. I tried various solutions but what helped me the most was [rehype-slug](https://github.com/rehypejs/rehype-slug)

**Comment by abbeyperini** [comment]
As stated in the description , I decided against rehype plugins.

Moving blogs per #16, so this will not be an issue.
